### ISSUE TITLE
keras.pb恢复模型报错

### ISSUE THREAD

**Issue by shanhedian2017** [gdyshi/model_deployment#1]

**Comment by shanhedian2017** [comment]
The name 'sequential_1:0' refers to a Tensor which does not exist. The operation, 'sequential_1', does not exist in the graph."

**Comment by gdyshi** [comment]
这是环境不一致导致的，我新增了requirement.txt文件，用于限制python包版本。
tensorflow==1.13.1
keras==2.2.4
numpy==1.16.2

**Comment by shanhedian2017** [comment]
sequential_1改成fc1就可以了，环境不用改
